@startuml

class Theme {

  - nom : String
}
class Question {
  - intituler : String
}
class Reponse {
  - intituler : String
  - isCorrect : bool
}
Question  "1..*" -- "1..1" Theme
Question "1..*" -- "4" Reponse
@enduml
